export const FETCH_DATA = 'FETCH_DATA';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const REMOVE_PACKAGE = 'REMOVE_PACKAGE';
export const ADD_PACKAGE = 'ADD_PACKAGE';
export const DISPLAY_MODAL = 'DISPLAY_MODAL';
export const UPDATE_PACKAGES = 'UPDATE_PACKAGES';
